INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Bark Off', 9.99, 'bark_off.jpg', 'A device that emits an ultra-sonic frequency that only dogs can hear. Warning this device can be viewed as an attack on the dog if left on.', 'A portable handheld device that uses an ultrasonic technology to stop your dog from barking.', 'BarkOff is safe and easy to use. Just switch it on and when your pet barks, it sends out an ultrasonic signal that will instantly capture their attention and interrupt their barking pattern. It wont hurt your pets ears and the signal it sends is completely inaudible to humans.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Clever Grip', 9.99, 'clever_grip.jpg', 'One way to keep your phone available for it''s features in your car, and keep you hands free while you access the important things. Like the GPS. Should not be used as an excuse to read or text while driving.', 'Introducing Clever Grip, the most portable smartphone car mount weve ever seen.Just attach Clever Grip on to any air vent and insert your smartphone. It helps eliminate fumbling searches, looking away from the road, and other unsafe behaviors.Also works as a travel stand.', 'It''s that simple. It keep your smartphone in sight at eye level and ready for GPS directions, streaming music, and hands-free calls.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Tiddy Bear', 9.95, 'TiddyBear.jpg', 'An item used to provide comfort in the care from the safety belt', 'Introducing the Tiddy Bear, the cute little guy made with the finest soft plush eliminates all these problems. Tiddy Bear is designed to make driving more comfortable.', 'Just snap the Tiddy Bear onto the shoulder strap of your seat belt and adjust up and down to remove pressure where you need it.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Crosswave', 299.99, 'crosswave.jpg', 'The perfect vacuum cleaner engineered specifically for pet owners. This vaccuum washed and vacuums the floors and rugs for easy and fast hair cleanup.', 'Vacuums and washes floors at the same time | Cleans both sealed hard floors and area rugsDual-action brush roll | Smart-Touch controls | 2-tank system |Integrated carrying handleEasy-remove brush window |', 'Swivel steering | Multi-surface cleaning solutionEasy-clean storage tray | Solution tank holds enough solution to clean up to 700 sq ftModel# 1785W | Dimensions: 10.50 x 12.00 x 46.00 Inches', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Haier portable air conditioner', 299.99, 'air_condition.jpg', 'If you need a great way to keep yourself cool, and have no central air or not enough window space, the Haier portable air conditioner will do the job', 'This 8,000-BTU portable air conditioner is ideal for spot cooling small rooms up to 250 square feet. With three cool settings, three fan settings, a 24-hour on/off timer and dehumidify mode, this single-hose model is equipped to meet your interior climate needs.', 'A Quick-Install Window Kit is included for exhausting the unit through any horizontal or vertical opening window and fully-directional casters provide mobility.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Magic Bullet', 39.99, 'magic_bullet.jpg', 'The perfect machine for all your smoothie, or blending needs. Easily portable.', 'As Seen on TV Magic Bullet, 17-Piece set:Chops, mixes, blends grinds and more1 high-torque power base2 stainless steel blades1 tall cup1 short cup2 shaker / steamer tops2 stay-fresh resealable lids4', '22oz oversized mugs4 colored lip rings for mugs17-piece blender with 100-page recipe book includedDoes kitchen jobs in 10 seconds or less The As Seen on TV Magic Bullet Express Blender and', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Shark Steam Mop', 119.99, 'shark_steam_mop.jpg', 'Steam cleans and sanitizes your floor. Great for hard wood, and removes grease and grime.', 'Shark Steam Pocket Mop... Patented 2-sided cleaning "pocket": clean with one side, and sanitize with the other for faster, more effective cleaning; Quick Release Mop Heads allow for easy cleaning of all spaces;', 'Longer cord and larger water tank for faster, longer cleaning. Includes the following: Rectangle Pocket Head, 20ft Power Cord, 1 Rectangle pockets and Filling flask. comes with one washable microfiber cleaing pads.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'The Clapper', 17.99, 'clapper.jpg', 'Great and easy way to turn off electronics without moving from where you are.', 'Control 1 or 2 things at the same time by simply clapping your hands.;Great for lamps and Christmas tree lights! CLAP ON, CLAP OFF;2 CLAPS/3 CLAPS SETTING:', 'connect to the 2 or 3 clap outlet, then activate each one with 2 or 3 claps respectively.;Features Clap Detection Lights: Lights glow in sequence when proper claps are detected.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Kaboom Foam-Tastic Cleaner', 13.99, 'Kaboom.jpg', 'A powerful cleaner that eliminates bathroom stains, buildups and soap scum, no hard scrubbing necessary.', 'Tired of tough scrubbing? Try Kaboom Foam-Tastic, a foaming cleaner that changes color to let you know the surface is clean. As it sprays on blue, the', 'OxiClean stain-fighting bubbles get to work powering through soap scum, hard water, and calcium and lime stains. When it turns white you just wipe away to reveal a deep clean and a sparkling shine with absolutely no dull residue left behind.', '2.6 x 2.6 x 9.5 inches ; 1.4 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'OxiClea', 9.99, 'oxiclean.jpg', 'A cleaning product that uses the power of oxygen to remove tough stains. Works great with clothes, and doesnt cause colors to bleed.', 'OxiClean Versatile Stain Remover Chlorine Free.', 'Concentrated! 99% Active stain fighters. 156+ loads. Now concentrated! Use less per load vs. previous formula! For all machines including HE.', '7.1 x 5.4 x 8 inches ; 7.22 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Roto Sweep', 19.99, 'sweep.jpg', 'hard floor sweeper that is a broom and dust pan all in one. Only works in one direction, but great for edging.', 'INTRODUCING THE ROTO SWEEP The Hard Floor sweeper from the Fuller Brush company! It&rsquo;s a rotating broom with a built-in dust pan that puts the power of cleaning any mess into the palm of your hand!', 'HOW IT WORKS - Manually push sweeper forward to collect dirt and debris. No bags, filters, batteries or electricity cords required. -', '15.5 x 8.7 x 3.9 inches ; 1.9 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Sani Sticks', 9.99, 'san_stick.jpg', 'A safe and powerful drain cleaner that cleans, deodorizes and prevents clogs in any kind of plumbing.', 'SMART CLEANING: Sani Sticks cleaner, deodorizer and clog preventer are a powerful, safe and efficient way to eliminate embarrassing, foul odors from drains and helps to prevent clog backups in sinks and showers. Its non-toxic formula is gentle and safe on septic tanks and is available in multiple scents and count varieties.', 'ONE STICK IS ALL IT TAKES: Made with powerful, natural enzymes, each Sani Stick slowly releases a super concentrated blend of powerful enzymes that will eliminate organic deposits and grease build up for 30 days.', '4.9 x 1.8 x 6.3 inches ; 8.5 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Scrub Daddy', 24.99, 'scrub_daddy.jpg', 'The sponge that keeps on giving and can handle al of your cleaning needs.', 'America''s favorite sponge! Safe on non-stick pans, stainless steel & other delicate surfaces. Test in small area before using. Dishwasher safe. Food may get stuck in my pores. Keep fresh by running under warm water after each use.', 'Scratch free. Resists odors. Soft in warm water & firm in cool water', '1.67x 4.05x 5.99 ; .06 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Shamwow!', 24.99, 'shamwow.jpg', 'The one time paper towel, holds up to 10 pounds its weight in liquid and machine washable.', 'The world famous ORIGINAL As-Seen-On-TV Shamwow! It''s like a Chamois (Shammy), Towel, and a Sponge, all in One. 8 piece set - 4 large towel cloths and 4 small towel cloths.', 'The massive ShamWow towels are 20 x 23.5 inches and the minis are 15 x 15 inches You can cut the large ones in half to use as a bath mat, drain your dishes, under your crisper to keep the veggies fresh and even make smaller ones for dish rags.', '12.6 x 10.7 x 2.9 inches ; 12 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'True touch', 12.99, 'true_touch.jpg', 'A great way to spend time with your hairy pets, groom them, and get that excess hair off of them.', 'Pet the Hair Away! Great for all Dogs & Cats. Your pet will love the True Touch Five Finger Deshedding Glove! It mimics the loving touch of your hand for a relaxing massage and includes 180 soft silicone grooming tips to groom your pet with ease.', 'The hair sticks to the glove, making it easy to peel and throw away. Minimize shedding and keep your house clean with the True Touch Deshedding Glove.', '7.8 x 0.5 x 10 inches ; 2.88 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Flex Tape', 4.99, 'Flex_Tape.jpg', 'A super strong, rubberized, waterproof tape that can patch, bond, seal and repair virtually everything!', 'Flex Tape Rubberized Waterproof Tape, 4" x 5'', Black', null, '4.2 x 3.5 x 3.5 inches ; 2.4 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Hercules Hooks', 7.99, 'hercules_hooks.jpg', 'A hook that installs with no tools, and can hold up to 150 pounds.', 'The Hercules Hook is the easiest way to hang pictures mirrors shelves just about anything. Hercules Hooks are easy to install just twist push and turn! No more drilling or pounding to try to find a stud - No more damaged walls!', 'The reinforced steel design provides the muscle to hang and hold up to 150 lbs.', '11.2 x 5.7 x 2 inches ; 3.2 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Mighty Putty', 9.95, 'Mighty_Putty.jpg', 'A strong putty that is useful for sealing holes and other such things.', 'Now you can repair any job big or small, thanks to Mighty Putty. Mighty Putty is great for anything from your smallest craft projects to your largest home improvements.', 'The easy way to fix, fill and seal almost any surface, and make it last. Mighty Putty is a powerful bonding epoxy stick that you can mold to any shape .', '1.2 x 5.8 x 6.8 inches ; 5.8 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Pressure Joe 1450-PSI Electric Pressure Washer', 84.99, 'Pressure_washer.jpg', 'A cleaner for light to medium jobs, using the power of water.', 'The ultimate dirt fighter, the Pressure Joe SPX1000 is ideal for tackling a variety of light-to-medium duty cleaning jobs. Use it to clean boats, motorcycles,', 'RV''s, ATV''s, trailers, decks, barbecues, siding and more. Packed with a powerful 1400-watt motor, Pressure Joe delivers up to 1450 PSI of cleaning power and a maximum', '12 x 9.8 x 19 inches ; 11.7 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Rodent Sheriff', 7.95, 'rodent_sherrif.jpg', 'Uses natural peppermin oil to get rid of mice, rats and other pests.', 'A powerful spray made in the USA from a handcrafted peppermint formula. Youll love its long-lasting minty fresh scent, but mice, roaches, raccoons and other rodents hate it. So the minute they get a whiff, they head for the hills.', 'And since its a natural formula, you can even spray it around your garden, around trash cans, vehicles, garages, storage areas, attics, entry points around your house...', '10 x 4.2 x 3.5 inches ; 1.5 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Zapp Light', 12.99, 'zapp_light.jpg', 'A light bulb and a bug zapper all wrapped in one. Help keep your mosquito problems down.', 'As Seen On TV Light Bug Zapper 60 watts 600 lumens 4000 K LED A19 Bright White 9 watts Equivalency. Low consumption. Energy SavingSpecifications. Color White', null, '8.3 x 5.9 x 3.2 inches ; 5.35 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Bowflex', 539.99, 'bowflex.png', 'Great in home gym to be used for heavy lifting and toning. Comes with a variety of workouts.', 'The Bowflex Ultimate 2 Home Gym is a total body solution that delivers everything you could possibly imagine for great fitness results.', 'It offers over 95 exercises and includes a lat tower, leg extension/leg curlstation, preacher curl, integrated squat station and more.', '468 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'GLH Hair System', 39.95, 'GLH.jpg', 'A powder that attaches to the smallest of hair follicles and builds on itself to act like hair.', 'Glh is the very latest breakthrough and contains almost life-like fibers that instantly give added body to your hair. Glh will take away that wispy look. Fill in those thin see-through spots and for men it can even cover bald spots. It''s like instant hair in a can. If you have tried everything give Glh a go. A fantastic new hair product that will end bad hair days forever. Our users make comments like "It is just marvelous". You may have seen Glh on Tv including The Panel, news services and even on movies like Mighty Joe Young, Fight Club, Ten Things I Hate About You, The Green Mile and our early products Lobo and Mane in The Fabulous Baker Boys.', null, '8.8 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Hawaii Chair', 49.99, 'hula_chair.jpg', 'A kind of swiveling chair that consistently moves in a circle and provides an abdominal work out.', 'This is a brand new Hawaii Chair (Hula Chair) and is built with steel feet, ABS armrest and leather backrest. Great gift for ladies!', '9 Speeds with 60 Watt Power and Handle up to 300 Lbs. Exercises the whole body especially the waist. Strengthening intestines and stomach functions while stimulating blood flow', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'InStyler Max 2', 19.99, 'instyler.jpg', 'The rotating iron, styles and dries your hair off at the same time.', 'The MAX is the most advanced version of the InStyler rotating iron yet. The 2-way rotating barrel''s innovative technology allows for change of direction with a simple double-click', 'of the barrel for maximum results by rotating in the natural direction of your hair. With a tourmaline ceramic smoothing plate, dual rotating barrel and ionic bristles, the MAX straightens,', '12 x 5.5 x 2.6 inches ; 1.4 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Kush', 39.99, 'kush.jpg', 'An item made to support the breasts while sleep', 'Breast support for side sleepers, cup size C and larger - Kush Support provides the support your breasts need for comfortable sleep.', 'Yet Kush Support is so lightweight and comfortable that it feels like part of your body. Foam adapts to your skin temperature.', '6.5 x 4 x 3.9 inches ; 2.08 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Proactiv', 34.99, 'proactiv.jpg', 'Have a problem with acne? Proactiv is the dermatologists choice in handling clogs pores and keeping your face clean.', 'The Proactiv 3-Step System helps treat and prevent acne breakouts with proven acne-fighting ingredients. The Renewing Cleanser and Repairing Treatment contain benzoyl peroxide,', 'a proven acne medicine known to kill and prevent acne bacteria. The alcohol-free Revitalizing Toner helps to gently remove excess oil and soften acne-prone skin with glycolic acid.', '9 x 2.8 x 1.3 inches; 1.2 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Rejuvenique Electric Facial Mask', 99.99, 'Rejuvenique.jpg', 'A great Halloween mask and facial toner. This tool was advertised as a product that would reduce wrinkles. Requires a 9-volt battery.', 'Set includes: rejuvenique mask adjustable, washable headband control handset cable connector 9 volt battery owner s manual', 'By delivering a light pulsation from a 9-volt battery (included), the 26 gold-plated contact points inside this facemask gradually tone the skin and reduce the appearance of wrinkling.', '10.5 x 3.8 x 11.2 inches ; 1 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Shake Weight', 19.99, 'ShakeWeight.jpg', 'A training tool for the arms.', 'Get incredible results in just 6 minutes a day using the revolutionary new way to shape and tone your arms, shoulders and chest It''s fun and easy to use. The Shake Weight for Women is designed specifically for Women and utilizes new workout technology called Dynamic Inertia, which can increase muscle activity to nearly 300 percent compared to a standard dumbbell.', null, '13.4 x 4 x 5.4 inches ; 3 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Sweatin? to the oldies', 9.99, 'sweatin_to_the_oldies.jpg', 'A classic work out video featuring Richard Simmons, and some classy music. Lose yourself and some pounds by tuning into this vigorous work out.', 'Turn back time with America''s Favorite Fitness Expert, Richard Simmons! Celebrating 25 years since the original Sweati'' to the Oldies, fall in love with fun fitness all over agai', 'with this low impact routine guaranteed to get you off the couch and getting into shape.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'ThighMaster', 12.99, 'ThighMaster.jpg', 'A product that can be used to tone legs and arms for multiple work outs.', 'It''s the ThighMaster Gold and the ButtMaster (LBX) together for the ultimate lower body workout. This is the only original ThighMaster straight from Suzanne Somers. Do''t accept any knock-off brands.', 'Both tools aid in sculpting arms, shoulders, chest and back. It''s the fast, easy, and inexpensive way to get in shape. Comes with an instructional DVD.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'George Forman Grill', 99.99, 'george_foreman.jpg', 'The amazing grill that cooks your food evenly, while reducing the fat in any meats you cook. This item can be used in a variety of different dishes from Panini''s to steaks.', 'The George Foreman GR144 Silver Grand Champ Family Size Indoor Grill is great for any family large or small. Get all the space you need to cook leaner for up to 9 people with our largest indoor contact grill. The 144 Sq. In. grilling surface easily fits up to 9 servings, with even heat from the center to the sides of the plate with our Signature Foreman heating elements. Our patented sloped design and George Tough™ nonstick coating allow you to cook without oil or butter while fat and grease drain off for leaner meals in minutes. The grill includes a dishwasher safe drip tray for added convenience.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Ginsu knives', 79.99, 'ginsu_knives.jpg', 'The perfect knives to get if you need to cut through a can and then slice a tomato right after.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Slap Chop', 24.99, 'slap_chop.jpg', 'A great product to use for chopping and mincing vegetables.', 'STAINLESS STEEL & LARGE CUP CONTAINER: Slap Chop blades are made of the highest quality stainless steel while the convenient large cup container captures all foods that are chopped. High quality blades quickly deskin the garlic and onions in seconds.', 'EASY TO CLEAN: Unlike the generic store ones Slap Chop easily pops open like a butterfly for easy access while cleaning. Cleaning becomes as easy as three simple steps: Remove base, remove cup, and pop open like a butterfly. PERFECT FOR ALL KINDS OF FOOD: With just one slap you have big chunks and the more you slap the finer it gets. Its the perfect way for making salad, pizza toppings, exciting tuna, breakfast to go, nuts and cookies for ice cream toppings, fruit salad, and many more foods. ORIGINAL SLAP CHOP: The original slap chop is the perfect chopper to mince and chop a variety of ingredients for easy meal preparation or final touches. Its easy to push-down handle allows for quick chops with almost no effort. All orders come with original packaging. Slap Chop is a manual chopper machine that chops food when you slap the plunger.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Chia pet', 17.99, 'chia_pets.jpg', 'Trying to brighten up your office, or home. Why not spruce it up by growing a plant on a fake animal or face via the chia pet. Trust us this is cheaper than a put.', 'Collecting and growing Chia Pet pottery planters has become an American tradition. Everybody loves Chia Pets! Kids and grown ups alike will enjoy "watching them grow!"Chia Pets are easy to grow making them a perfect first plant growing experience for kids. Makes a great gift! Collect them all!', 'Easy to grow with full growth in 1-2 weeks. Soak Chia planter in water; spread moistened seeds on tree; Keep Chia filled with water and seeds moist; Seeds will sprout in 3-5 days. Watch it grow!', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Energizer Solar landscape light', 79.99, 'Solar.jpg', 'Need to light up your yard? Well with this set of solar lights you can do just that.', 'Brighten the night with this 10-piece Energizer landscape light set. Each one is equipped with a crystalline solar panel that charges the light during the day, and then powers its gentle glow for up to eight hours a night. Use the set to line your walkway, deck, or patio, and enjoy a soft, charming ambience for outdoor gatherings, late-night cocktails, or more surefooted stepping. From Energizer.', 'Includes 10 lights and 10 AA NiMH batteries. Crystalline solar panel. Prism glass lens. Metal construction. Plastic stakes. For outdoor use only', 'Measurements: Light 15-1/2"H x 6"Diam; Stake 5"L');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'ShoeDini', 9.99, 'shoedini.jpg', 'The simple tool used to get your shoes on and off whithout the need to bend down. Perfect for those whith back issues.', 'Shoedini Shoe Horn extends to almost 3 feet to give you the extra reach you need!', 'Build in clip to slip your shoes off with ease. Easy to assemble.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Snuggie', 19.99, 'Snuggie.jpg', 'A warm blanket you can wear.', 'The Snuggie Blanket keeps you totally warm and gives you the freedom to use your hands. Work the remote, use your laptop or do some reading in total warmth and comfort! Put an end to those cold days and nights. The Snuggie Blanket is one of a kind with cuffed sleeves and a waist tie to keep you warm no matter what you''re doing!', null, '12.3 x 11.3 x 5.6 inches ; 1.26 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Tub Shroom', 9.99, 'tub_shroom.jpg', 'A great way to stop all of that hair and clunky sludge from going down your drain.', 'We face a myriad of challenges each and every day. Cleaning clogged drains, thankfully, no longer has to be one of them--thanks to the TubShroom. TubShroom is a bathtub hair stopper that fits snug inside your shower tub drain, effortlessly gathering each and every hair that tries to make its way down your vulnerable drain. It''s the hero you deserve in your bathroom. You can rest easy knowing that TubShroom works great for all kinds of hair-- human and pet alike. No more exorbitant bills from the plumber and no more having to use harmful chemical-based drain cleaners that damage your pipes.', null, '2.2 x 2.2 x 2 inches ; 0.48 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Wearable Towel', 19.99, 'WearableTowel.jpg', 'A towel that you can wear, alleviates the issue of holding up towel after shower.', 'The Wearable Towel has three arm openings placed along the side and does not employ the use of any fasteners. It is for unisex and can be worn in either a tunic style or a toga style.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Bendaroos', 19.99, 'bendaroos.jpg', 'A great toy for kids that is hard to break and can be used to make art, or amazing designs for massive fun.', '500 piece bendy toy', null, '10.6 x 8.8 x 2 inches');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Floam', 9.99, 'floam.jpg', 'A squishy and less messy version of slime and floopy stuff. It makes noise when squished just right, feels fun, and is malleable. (Keep in sealed place to prevent product from drying out too fast.)', 'Squishy foamy goop.', null, '9.6 x 5.2 x 4.9 inches');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Fushigi', 14.99, 'fushigi.jpg', 'The gravity ball is an illusory object that will leave you mistified in how the ball moves but does''t seem too, a cool but simple item that can be used to pass those bored hours that pas you by.', 'Brand New Fushigi Magic Gravity Ball No Strings No Tricks Simple Hand Manipulation will make Fushigi appear to Float and Defy Gravity Free DVD to Help', 'Learn Dozens of Illusions Great Gift for Teens- Adults-Mom-Dad Great Easter Basket Filler-Birthdays Novelty Gift and More', '7 x 7 x 5 ; 15.2 ounces');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Magic sand', 9.99, 'magic_sand.jpg', 'Designer sand perfect for building aquatic structures and things. Stays dry when put in water.', 'Sand that stays dry when wet', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Moon Sand', 19.99, 'moon_sand.jpg', 'Ever want to make that awesome sand castle without the hastle of going to the beach or dealing with sand everywhere. Well Moon sand will solve most of that problem. This sticky substance can be used to form all sorts of different things and will keep their form unless enough force is added. A great addition if you like scultping, or just want to distract your kids.', 'Shape It! Sand will mold like dough and never dries out. Add a new element to a sensory center and watch children create and experiment with a variety of colors. Non-toxic, dust-free and soft to the touch. White, 20 pound package. Ages 3 and up.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Pillow Pets', 27.99, 'pillow_pets.jpg', 'Ever wanted to cuddle up next to your favorite animal? Well now you can with these plush animals you will never want to sleep without. Except when you do want too.', 'Brand New 100% Authentic Pillow Pets Premium Large 18" AS SEEN ON TV and comes with all original Tags. In stock and ready to ship within 24 hours.', null, '17.8 x 12.5 x 7.8 inches ; 1.24 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Potty Putter', 10.99, 'putter.jpg', 'A toy golf set to be set up in the bathroom.', 'Arrives Before Christmas! The toilet time golf game that lets you practice your putting while going to the bathroom Sure it sounds funny, but for the golfer that just ca''t get enough of the game,', 'it''s the perfect item Makes the perfect gift for any golf fan of any age!', '7.2 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Zhu Zhu Pets', 59.99, 'Zhu_Zhu.jpg', 'Plucky and plushy, these robotics hamster move on their own and are interactive. have fun with your adventurous or nurturing hamster today, your choice in setting.', 'Chatter, scatter, scoot '' scurry like a real hamster.', null, '6.1 x 4.1 x 2.7 inches ; 1 pounds');
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Night Sight Glasses', 29.99, 'Night_Sight_Glasses.jpg', 'Night Sight Glasses the amazing HD driving glasses that turn night into day. Night Sight polarized HD night-driving glasses reduce glare and eye strain from lights at night.', 'Night Sight Glasses practically turn night into day with their polarized lenses. They cut down glare and the anti-reflective coating sharpens your view so you can clearly see everything in front of you. Its like watching the road in crystal clear high-definition.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Tiger Wrench', 24.99, 'Tiger_Wrench.jpg', 'Tiger Wrench is the uniquely designed tool that combines 48 tools into one and makes any repair quick & easy! By simply clicking between the different sizes you instantly have the tool you need for the job! Tiger Wrench as seen on TV is fast, and you need fast!', 'With Tiger Wrench youll always have the right tool for the job. Tiger Wrench can click to a 45 degree angle to get those difficult to reach nuts and bolts. Tiger Wrench is a thick, heavy duty, professional tool thats designed to tackle all your projects around the house, in the shop, or on the job!', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Cami Secret', 19.95, 'Cami_Secret.jpg', 'Cami Secret the quick and easy clip-on, mock camisole. Cami Secret as seen on TV allows you to control the amount of cleavage you want show.', 'Wear your favorite low cut blouse to work, and then meet for dinner date without having to run home to change  you can adjust or completely remove Cami Secret in seconds so you quickly have the perfectly appropriate outfit for any situation. Now you can have the layered look without the bulk with Cami Secret seen on TV.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Arctic Hat', 24.95, 'Arctic_Hat.png', 'Arctic Hat is the new hat that combines controlled evaporative cooling and UV protection from the suns visible and invisible rays. Arctic Hat''s evaporative cooling inner liner retains cool water and slowly evaporates to keep your head up 20&deg;F cooler. Simply wet the inner lining and put on the hat! Get instant relief from the heat and stay cool for hours.', 'Arctic Hat also has a built-in radiant barrier to deflect and block 99% of the suns harmful UV rays and reflects 80% of the su''s heat. Arctic Hat is made from a durable, breathable and lightweight construction. The same technology is used by professional athletes, the US military, and emergency services. Best of all, Arctic Hat is adjustable, so one size fits most! Perfect for the whole family!', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Turbo Pump Replacement Filter', 19.99, 'Turbo_Pump.jpg', 'Keep your Turbo Pump operating at its best and filter out particles and contaminates from the liquids you''re transferring with the Turbo Pump replacement filters. Just pop the head off of the inlet, snap in a new filter, and you''re good to go! Works with Turbo Pump and Turbo Pump Deluxe.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Diamotech Fry Pa', 29.99, 'Diamotech_Fry_Pan.jpg', 'Say Good Bye to cheap colored non-stick cookware and Hello to Diamotech with a non-stick ceramic coating infused with Diamotechs natural composition for effortless food release and cleanup.', 'Features uniform heat distribution for even cooking and better tasting meals thanks to its innovative 4-layer design with enforced construction. Works on virtually any cook top and can go from stove top or oven to the table. The ergonomic handle stays cool to the touch and cleanup is a breeze.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Perfect Bacon Bowl', 19.95, 'Bacon_Bowl.jpg', 'Perfect Bacon Bowl makes a whole new way to munch. Just wrap your favorite cut of bacon around the Perfect Bacon Bowl as seen on TV form and cook. The easy way to make delicious, edible bowls out of bacon for fun, savory, crunch-able yum. In just minutes you''ll have tasty, toasty, Perfect Bacon Bowls. The unique design allows the bacon to crisp up evenly while grease collects in the channel so you can pour it out of your diet. Now everything''s better in a Perfect Bacon Bowl. Perfect Bacon Bowl cooks bacon perfection in the oven, microwave and toaster oven too.', 'Kids want mac and cheese? Serve the perfect portion that''s sure to please. Craving burgers on game night? Stack ''em up in Perfect Bacon Bowls and pile on the toppings. And try this, a bacon bowl ice cream sundae. Salty, sweet, and fun to eat. Perfect Bacon Bowl makes bacon the star of every dish. And it''s not just for bacon, make mouth watering bread bowls for pizza bites, soups, stews, and more! And it''s all dishwasher safe, so clean up''s a breeze.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Hidden Wall Safe', 16.99, 'Hidden_Wall_Safe.jpg', 'Hide your valuables in this ordinary-looking power outlet that''s secretly a hidden wall safe! Designed to fool the smartest thief, Hidden Wall Safe Outlet can hide your money, jewelry and valuables.', 'Easy to install, no need to remove any existing outlets. Comes with template and drywall saw.', 'Does your home have brass, aluminum, wood, or other decorative outlet covers? No problem - your wall safe plate can be changed to match the decor of your home by removing the screw, bolt and locking washer and replacing it with any other face plate!', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Lizard Cam', 49.99, 'Lizard_Cam.jpg', 'Lizard Cam by Atomic Beam is the flexible, micro-inspection camera that snakes into tight, hard-to-reach spaces. Its easy to use just feed and view. The 4-foot long cable bends and flexes to fit into your desired space. At the end of the waterproof cable is a micro camera with a built-in LED light that sees all. View everything that the camera captures on the hand-held view screen. Use the snake camera beyond pipes and clogs. Attach the magnetic tip to the end of the cable and easily pick up screws, nails or other hardware youve dropped but cant see. Look behind or underneath appliances without having to move them. Retrieve lost cat toys from under the refrigerator with the handy hook tip. Lizard Cam is a must-have tool.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Flow Cable', 29.95, 'Flow_Cable.jpg', 'Most USB and iPhone / Apple charging cables are''t what you would call "cool," but this one definitely is!', 'When you plug in your device to charge, the cable itself lights up with pulses of glowing blue that appear to move down the cable from the power source to your device. What could be cooler than that?', 'This is a two-in-one cable, compatible with both Apple and Android devices. The certified Apple Lightning connector works with all of Apple''s recent devices -- all iPhones from the iPhone 5 onward, all iPads from generation 4 and later, all iPad minis, iPod Touch 5th generation and later, and the iPod Nano 7th generation and later. For Android devices, this cable also has a micro USB connector that will work with most Android phones and tablets.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Flex Mat', 25.99, 'Flex_Mat.jpg', 'Flexmat is the portable tool tray with flex. Flexmat is designed to keep your tools organized and within reach no matter the type of project. The multi-purpose, non-slip tool mat is made of ultra durable silicone that bends and flexes to work on virtually any surface. Protects surfaces from scratches and dents.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Micro Mechanic', 45.95, 'Micro_Mechanic.jpg', 'Micro Mechanic is the quick and easy way to diagnose and read your vehicles check engine light. When your check engine light comes on, just plug Micro Mechanic into the diagnostic port under your steering wheel. Micro Mechanic instantly shows you whats wrong and how severe the problem is, so you can determine the best course of action.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Tac Light', 19.99, 'Tac_Light.jpg', 'Made from aircraft-grade aluminum, the Taclight features 5 modes and zoom function, and can be seen up to two nautical miles away. Compact lightweight, extending over 6&quote; long with LED''s that will last up to 100,000 hours!', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Cop Cam', 39.95, 'Cop_Cam.jpg', 'Home security camera system can be costly and difficult to install. Cop Cam by Atomic Beam is the affordable, wireless security camera, measures less than one square inch and can hide virtually anywhere. Set it on a shelf or mount it on a wall.', 'The Cop Cam is equipped with a high definition camera that records in HD video and the powerful microphone records great audio for best footage possible.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Pocket Jump Starter', 69.99, 'Pocket-Jump_Starter.jpg', 'No more bothering with bulky jumper cables - jump start your car with the compact Pocket Jump Starter!', 'This pocket-sized portable battery charger allows you to power up a dead car battery, or even start your vehicle with no battery at all!', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (3, 'Portable Breathalizer', 19.99, 'Portable_Breathalizer.jpg', 'This portable breathalyzer provides quick and accurate results in seconds, and can help you avoid a dangerous (and costly) DUI!', 'The alcohol detection sensor in our portable breathalyzer is sensitive enough to detect presence of alcohol with considerable BAC accuracy. Check before you go! Requires 2 AAA batteries (not included).', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Stretchable Seat Cover', 19.99, 'Stretch_Seat.jpg', 'Chair covers stretch to fit oblong, square, round shaped chair seats. Hides wear and tear, rips, and tattered edges. Elastic edge holds cover securely in place. Fits office chairs, dining room chairs, bar stools, patio chairs, and more. Machine washable.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Arctic Air Replacement', 14.99, 'Arctic_Rep.jpg', 'Keep your air cool and clean all year with Arctic Air Replacement Filters. For best results change your filter every 3 - 6 months to keep your Arctic Air running a peak performance.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Clean Step Mat', 39.99, 'Clean_Step.jpg', 'Clean Step Mat''s secret is millions of super absorbent fibers that absorb mud and water like magic. Just step to clean - No need to wipe your feet! Clean Step Mat, as seen on TV, soaks up mud, rain, snow, slush and sleet. No more messy floors. Great for the front door, back door, garage door or wherever there is a door! Perfect for kids and pets. Made of 55% cotton and 45% microfiber.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Pocket Hose Top Brass Bullet', 39.99, 'Pocket_Hose.jpg', 'The Pocket Hose Top Brass Bullet as seen on TV is the easiest, lightest, toughest and most convenient hose you will ever use!', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Egg Sitter', 59.99, 'Egg_Sit.jpg', 'Egg Sitter Support Cushion allows you to sit on a hard surface all day and still feel comfortable. Other support cushions need a gap in the center to cradle the tailbone - not Egg Sitter! Its honey comb design is made of ultra-flex polymer that stays cool to the touch and allows air to circulate. It collapses in on itself to absorb pressure points and alleviate pain.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (5, 'Baseboard Buddy', 39.99, 'Baseboard_buddy.jpg', 'Baseboard Buddy is the newest and most efficient way to avoid the backbreaking, tedious work of cleaning baseboards on hands and knees. The extender rod allows for the easy gripping and the ability to stand the duster upright. Baseboard Buddy''s brilliant Flex Head design allows you to dust with 360 degree angle Swivel Action without any strenuous exercise and movements in awkward positions that can result in back pain and sore limbs. Ideal for the home or office, this unique microfiber duster is suitable for dusting other hard surfaces in addition to baseboards such as chair rails and crown molding. Clean your baseboards the fast and easy way with Baseboard Buddy!', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Hydro Rug', 29.99, 'Hydro_Rug.jpg', 'Hydro Rug the carpet for your shower and bath. Place Hydro Rug''s, as seen on TV, directly over the drain, the unique anti-microbial poly-fibers allow water to flow right through it and the non-slid backing ensures it stay were you put it. Hydro Rug is perfect the bath or shower. Hydro Rug is mildew and stain resistant. It''s fast drying and never wears out. Get rid of those soggy, smelly, mildewed mats - buy Hydro Rug now!', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Zip Trim Cordless Trimmer', 24.99, 'Zip_Trim.jpg', 'The Zip Trim Cordless Weed Trimmer is the portable trimmer that does it all by putting the RPM power of a traditional trimmer in the palm of your hand. No more expense, or mess and fuss related to gas or electric trimmers.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Dust Daddy', 29.99, 'Dust_Daddy.jpg', 'Dust Daddy uses dozens of individual, tiny suction tubes. These tiny tubes are flexible and unlike other cleaning tools, they can go nearly anywhere dust hides. Clean around tiny objects without removing them first. Perfect for cleaning around fragile objects.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'FabriClear', 14.99, 'Fabri_Clear.jpg', 'FabriClear kills bed bugs, dust mites and their eggs, larvae by contact. Bed bugs can be found in homes, offices, hospitals and hotels and even though your sheets may look clean, those bloodsucking bed bugs could be hiding between them. No need to fear, ready-to-use FrabriClear, as seen on TV, has formulated a solution to help combat the bed bug outbreak by contact.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Clean Reach', 19.99, 'Clean_Reach.jpg', 'Do''t break your back doing your housework. Effortlessly clean all those hard-to-reach places with the versatile Clean Reach extendable scrubbing brush. As seen on TV, the CleanReach is a revolutionary ergonomic scrub brush that allows you to effectively scrub every surface without having to bend or kneel to reach every surface. Protect your hands from the harsh cleaning chemicals by using this convenient touch-free tool. The ergonomic handle extends to 33&quote;, just the right length to reach all those impossible-to-reach spaces, and the contoured non-scratch scrub pad angles into every position to do all the dirty work. Cleanup is a breeze  simply rinse and relax. It could''t be easier!', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Turbo Scrub', 29.99, 'Turbo_Scrub.jpg', 'Turbo Scrub is the cordless, rechargeable hand held power scrubber that will take the work out of cleaning! Its powerful head rotates at over 300 revolutions per minute so you can scrub and clean with minimal effort. The lightweight, maneuverable design allows you to clean in those hard to reach places.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Breath Easy humidifier', 59.99, 'Breath_Easy.jpg', 'Breathe Easy Humidifier eliminates dry air that can irritate and inflame nasal passages and throat. Breathe Easy Humidifiers cool mist technology provides the much-needed moisture to your home, for comfortable breathing. Perfect for relieving the discomfort of cold, flu, allergies and dry weather. Winter and heat dry out the air. Heaters and fireplaces also strip away moisture. Breathe Easy Humidifier gives you relief from the dry air. No more dry, scratchy eyes, nose and throat.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Dryer Max Dryer Balls', 24.99, 'Dryer_Max.jpg', 'Dryer balls are the safe, natural, easy way to soften fabrics while saving money on chemical fabric softeners, dryer sheets, and energy.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (2, 'Spin Spa Body Brush', 19.99, 'Spin_Spa.jpg', 'Spin Spa the spinning body brush will pamper you from head to toe. As seen on TV Spin Spas five attachments buff, cleanse, massage and exfoliate skin for that all over glow you once could only get from costly spa treatments. Extra-long handle extends your reach to target back and lower legs. Spin Spa works with your favorite soap or body wash for every day cleaning. Helps promote healthier, younger looking skin.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Pops A Dent', 29.99, 'Pop_A_Dent.jpg', 'Developed and utilized by professional auto-body experts. Unique patent-pending arched bridge design eliminates the chance for additional damage. Other systems without this design are known to actually add dents to the surface. The bridge tool is designed with a flex-n-pull feature that allows the tool to flex as it pulls creating maximum pulling power.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Lint Magic', 19.99, 'Lint_Magic.jpg', 'Lint Magic picks up lint, pet hair, dust and more and then it cleans itself like Magic! With the Lint Magic, there are no refills to buy ever! When it is full just empty it out. It is reusable over and over again. Great for clothes, carpets, couches ,car seats and more.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Bed Bug Blockade', 59.99, 'Bed_Bug.jpg', 'Ideaworks Bed Bug Blockade Mattress Cover protects against bed bugs, dust mites, and allergy symptoms.', 'The chemical-free high density Polypropylene material is an effective barrier to help protect against bed bugs, dust mites and allergens. Machine washable. 3-sided zipper lock.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Buck Light', 24.99, 'Buck_Light.jpg', 'Buck Lights are powerful LED flashlight, the ultra-bright LED bulb lasts over 100,000 hours and the handy, lightweight, compact size let you use them anywhere and keep them anywhere.', 'A press on the button turns it on to shine an intense beam wherever you need it. Brightens the house or car door lock for fast, fumble-free entry. Great for when you need a light checking out a restaurant menu, looking in your purse, fuse box, under car seat, anywhere! Dont get caught in the dark ever again.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Couch Coster', 19.99, 'Couch_Coaster.jpg', 'Couch Coaster is the ultimate drink holder for your couches and chairs. Couch Coaster keeps your furniture safe from spills and beverage within reach. This one-size-fits-all drink coaster securely holds all your favorite drinks, hot or cold, on your sofa, couch, armchair or recliner. Your beverage stays upright, secure and within reach.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (0, 'Atomic Beam Headlight', 39.99, 'Atomic_Beam.jpg', 'Do''t get stuck in the dark! Atomic Beam Headlight is the ultra-bright tactical headlight. The military uses some of the most powerful lighting in the world, and now that technology is yours to use at home with Atomic Beam Headlight! Atomic Beam Headlight is stronger and brighter than regular flashlights.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Star Night Laser', 59.99, 'Star_Night.jpg', 'The most spectacular way to decorate your home instantly! Just plug them in, point and thousands of big, bold breathtaking stars appear right before your eyes! The secret is advanced laser light technology that creates a dramatic 3-D effect. You will feel like you are in the middle of a cosmic star field. With 8 different design patterns to choose from- brilliant red, super bright green, or click BOTH for red and green!', 'Choose between the original Star Night lights (solid) and the Star Night Motion Lights which blink, flash and even give you a carousel of fun patterns to light up your home.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Handy Heater', 59.99, 'Handy_Heat.jpg', 'Handy Heater plugs right into any outlet without taking up any space to give you a warm and cozy place to relax! It''s the quick, easy way to heat up to 250 square feet without expensive heating bills.', 'Turn cold and chilly spaces into warm and cozy places for just pennies a day. Just set the digital thermostat to the temperature you want, and Handy Heater will turn on and off automatically.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Air Hawk w/ Bonus Battery', 79.99, 'Air_Hawk.jpg', 'Air Hawk is a cordless, handheld air compressor that pulls in outside air and compresses it into the tire. It''s fast, easy to use, and extremely convenient. No more driving to the gas station or pulling out a large air compressor just to fill your tires.', 'Air Hawk features a built-in digital pressure gauge, and you can set it to automatically turn off once the desired pressure is reached.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Night Hawk', 49.99, 'Night_Hawk.jpg', 'Keep your home safe and secure with Night Hawk, the specially designed, super bright LED outdoor motion-sensor security spotlight! This powerful 450 lumen LED spotlight illuminates up to 675 sq. ft. of dark areas around your home. Night Hawk is motion activated from up to 36 feet away and automatically shuts off after 20 seconds of no motion. The sensor also keeps the spotlight from activating during the day.', 'Great for unlit outdoor areas around your home like backyards, sheds, doorways, garages, driveways, patios, decks and more! Perfect for indoor use in closets, under stair anywhere you need light.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Aqua Tunes', 39.99, 'Aqua_Tunes.jpg', 'Aqua Tunes lets you stream hours of music in wet environments. It''s universally compatible with all Android, iPhone, Windows Phone, iPad, tablets, iPods, MP3/MP4 players, or any device that supports audio over Bluetooth.', 'Aqua Tunes water-resistant design and built-in suction cup makes it great for showers and bath tubs, at the beach or pool, in the kitchen, or anywhere outdoors. And it does more than just stream music - Aqua Tunes has a built-in microphone and can also be used as a hands-free speakerphone!', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'One Charger', 19.99, 'One_Charger.jpg', 'One Charger is the ultimate, compact universal charge cable that works with ALL of your devices - iPhone, iPad, Android, Windows, GPS units, cameras, and more! One Charger features a dynamic charge tip that works in both micro USB ports and Apple Lightning ports, so you do''t need a separate charger for different devices, making it the LAST charger you''ll ever need! Traveling with an iPhone and a Windows tablet? Or an Android phone and an iPad? No problem - One Charger can charge them both.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Pocket Mouse', 29.99, 'Pocket_Mouse.jpg', 'Pocket Mouse the is a wireless optical mouse you hold like a pen with enhanced optical technology that let you work on any surface. The pen design and wireless technology replicate your hand movement.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (1, 'Sensor Brite', 19.99, 'Sensor_Brite.jpg', 'Why fumble in the dark getting out of bed or walking down the hall? Let Sensor Brite light your way! Sensor Bright is a motion-activated, light-sensitive LED that turns itself on and off, so you only have light when and where you need it!', 'The Sensor Brite lights instantly come on when detecting motion and automatically turn off after 30 seconds when no motion is detected. Features 3 super bright LED lights stay bright up to 50,000 hours, built-in sensor so it on comes on when it is dark. The sleek design make it perfect for', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Walkfit Platinum Orthotics', 29.95, 'Walkfit.jpg', 'WalkFit Platinum orthotic insoles evenly distribute the weight over the foot. They help relive discomfort and pressure on the foot, leg and spine to relieve pain in the ankle, knee, hip and lower back. These foot relief insoles are made of thermoplastic and rubber and are treated with silver to check the growth of odor-causing fungus and bacteria.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Perfect Smile Veneers', 29.99, 'Perfect_Smile.jpg', 'Perfect Smile is the amazing, removable veneer that instantly gives you the look of perfect teeth you''ll be proud to smile about. The secret? Perfect Smile is the groundbreaking veneer made with super comfortable, micro-thin Polypropylene. Just soak in hot water and press into your existing teeth for an instant, custom fit.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Simply Straight', 39.99, 'Simply_Staight.jpg', 'Simply Straight is the quick and easy way to get salon quality, perfectly straight hair. As seen on TV, this hair straightener brush glides through your hair like a regular hairbrush, giving you beautifully smooth, straight hair in minutes.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Strutz Cushioned Arch Supports', 14.99, 'Strutz_Cushioned.jpg', 'Strutz Cushioned Arch Supports, all day relief for achy feet. Strutz cushioned arch supports, as seen on tv, absorb shock with every step, while the comfortable compression band hugs your foot for maximum support and a perfect fit. Promotes good balance and body alignment. Wear with any shoe  even barefoot. Breathable polyester band with durable non-slip sole. One size fits all. Set of 2. Great for women and men. Buy Strutz Cushioned Arch Supports for all-day comfort and support!', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'DermaSuctio', 29.99, 'DermaSuc.jpg', 'Grossed out by your clogged pores? Looking for a better way of how to get rid of blackheads? DermaSuction effortlessly removes blackheads for a painless and easy blackhead removal.', 'Squeezing damages delicate skin tissue. And so-called blackhead remover masks often fall short of their claims. Derma Suction uses a powerful, yet gentle vacuum that extracts impurities and blackheads from your pores. With two different power settings, you choose the one thats right for you to remove dirt, oil and grit and reveal even looking and healthy complexion.', 'DermaSuction has 4 interchangeable suction heads for the perfect extraction. The oval head smooths areas with fine lines and stimulates circulation in the skin. The small head helps unclog and reduce blemishes great for sensitive skin. The large head provides deep cleaning of pores with strong suction to massage large areas of the body (torso, arms, legs and back). The sonic microdermabrasion head gently loosen and exfoliates dead skin. Reveal your beautiful skin. When youre done, simply rinse the dirty suction head under water. Waterproof.', null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'EZ Makeup Glasses', 19.99, 'EZ_Makeup.jpg', 'EZ Makeup Glasses the clever single lens eyeglasses that magnifies each eye to apply, and swings out of the way so you can have flawless makeup every day. As seen on TV EZ Makeup Glasses light up and have 3X magnification so you can see every detail. It is like having a magnifier and makeup lights all in one. The single-lens flips from one side to the other  applying eye makeup has never been so easy.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'MicroTouch Solo', 39.99, 'MicroTouch.jpg', 'MicroTouch Solo the hyper-advanced, smart razor that trims, shaves and edges all with the same blade. The German stainless steel dual sided blade lets you shave up or down with micro-precision. The pivoting head contours to your face for perfect comfort. Features built-in light.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, 'Sonic Pic Dental Cleaning System', 19.99, 'Sonic_Pic.jpg', 'Sonic Pic uses gentle sonic vibrations to remove stains and buildup, giving you whiter teeth and healthier gums. It cleans hard to reach places where food particles and plaque hides. Safe for implants, crowns, veneers and dental work.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (4, '3 Second Brow', 24.99, '3_Second.jpg', 'The 3 Second Brow eyebrow stamp is the perfect, easy way to natural-looking eyebrows in second! As seen on TV 3 Second Brows gives you perfectly symmetrical eyebrow in seconds. Whether you want to shape and define for fuller brows or fill in sparse eyebrow its easy with three second brow. Gently press stamp into the brow powder, place stamp on top of eyebrow and enjoy the beautiful brow you always dreamed of.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Magic Tracks RC Race Set', 39.95, 'M_T_RC.jpg', 'It''s the all new Magic Tracks Turbo RC! The amazing racetrack that can bend, flex and glow as the remote control car goes, goes, goes! Just snap any track pieces together and create your customized speedway that moves like magic.', 'Grab the remote and press go. The car burns rubber and zooms around the neon colored track. You can slam on the brakes, shift into reverse, honk the horn and more!', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Magic Tracks Extreme', 29.95, 'M_T_Extreme.jpg', 'Magic Tracks Extreme Mega Set the amazing race track that can bend, flex, and glow! Now with faster, brighter light-up race cars and glow in the dark track with glow trail technology.', 'Kids love Magic Tracks! The totally new cool race tracks that bend and glow like youve never seen before. You can bend, flex, and curve the track magically in 360 degree however you want - even while the race car is zooming around.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Magic Tracks Extreme Mega Set', 49.95, 'M_T_E_Mega_Set.jpg', 'Magic Tracks Extreme Mega Set the amazing race track that can bend, flex, and glow! Now with faster, brighter light-up race cars and glow in the dark track with glow trail technology.', 'Kids love Magic Tracks! The totally new cool race tracks that bend and glow like youve never seen before. You can bend, flex, and curve the track magically in 360 degree however you want - even while the race car is zooming around.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Zoom Tubes', 39.99, 'Zoom_Tubes.jpg', 'Zoom Tubes Car Trax with its twist and turn tubular trax is easy to build!', 'Just connect the tubular track to form any number of insane configurations, place the Zoom Racer in the Zoom Tube, activate the remote control and go! Watch it zoom up, zoom down, zoom all around.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Dream Tents', 29.99, 'Dream_Tents.jpg', 'As seen on TV Dream Tents are unique tents designed to fit up and over existing beds. Children can enjoy protection from the dark, scary things that come out at night. Dream Tents are easy to set up and easy to store. They pop open and fasten the bed in just seconds.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Nite Brites Slipers', 29.99, 'Nite_Brites_Slippers.jpg', 'Nite Brites are soft, cozy slippers that light up with each step you take. Kids will fall in love with all the adorable characters. As seen on TV Nite Brites use LED safe lights that never get warm and are activated by motion sensor, take a step or tap your feet, Nite Brites light up to your beat.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Mustache Pacifer', 11.99, 'Mustache_Pacifier.jpg', 'Make your baby the coolest kid on the block with this Mustache Pacifier!', 'Ordinary pacifiers only help stop babies from crying - but with the Mustache Pacifier, your baby can stop crying and look awesome doing it.', null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'MagicPad', 19.99, 'MagicPad.jpg', 'MagicPads unique screen is clear, but once your draw or write your art will glow super bright day or night. The secret is the color burst LEDs lights with illum-screen science, so you can sketch, draw or write them press the button to make everything glow  theres 8 different light effects! Then wipe clean and start all over again.', null, null, null);
INSERT product (product_cat, product_name, product_price, product_image, description1, description2, description3, product_dimensions) VALUES (6, 'Outlander Trail Tent', 119.99, 'Outlander_Trail_Tent.jpg', 'If you love to camp, but hate the hassle of pitching a tent, the Outlander Instant Tent is the one you want. Just take it out of the case and toss it in the air - and Instant Tent lands on the ground ready to use. It sets itself up in two seconds, and can be folded back up in ten!', 'With zipper openings and bug screens on both ends, interior pockets for storing your phone and other essentials, and room for two adults, the Instant Tent makes camping easy. And when you''re done, just fold it down and slip it back in the case.', null, null);


INSERT customerv2 (active,encrypted_password,user_role,username,a_additional_info,a_address,a_address2,a_city,a_country,a_home_phone,a_mobile_phone,a_state,a_zip,p_dob,p_email,p_first_name,p_last_name) VALUES (true,'38CPb85GBXZPIRM3HGICXQ7WhrosX0tZ+BcUxOp9916XhjLLBLac46n3hFJ9ry+U','customer','Michael',null,'1 Lane',null,'Town',null,'631-555-5555','631-555-5555','NY','11743','4/28/19','mike@lifo.website','Michael','Hern');



DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews (
                         reviews_id int NOT NULL auto_increment,
                         products_id int NOT NULL,
                         customers_id int,
                         customers_name varchar(255) NOT NULL,
                         reviews_rating int(1),
                         date_added datetime,
                         last_modified datetime,
                         reviews_status tinyint(1) NOT NULL default '0',
                         reviews_read int(5) NOT NULL default '0',
                         PRIMARY KEY (reviews_id),
                         KEY idx_reviews_products_id (products_id),
                         KEY idx_reviews_customers_id (customers_id)
);


DROP TABLE IF EXISTS tax_rates;
CREATE TABLE tax_rates (
                           tax_rates_id int NOT NULL auto_increment,
                           tax_rate decimal(7,4) NOT NULL,
                           tax_description varchar(255) NOT NULL,
                           last_modified datetime NULL,
                           date_added datetime NOT NULL,
                           PRIMARY KEY (tax_rates_id)
);

DROP TABLE IF EXISTS specials;
CREATE TABLE specials (
                          specials_id int NOT NULL auto_increment,
                          products_id int NOT NULL,
                          specials_new_products_price decimal(15,4) NOT NULL,
                          specials_date_added datetime,
                          specials_last_modified datetime,
                          expires_date datetime,
                          date_status_change datetime,
                          status int(1) NOT NULL DEFAULT '1',
                          PRIMARY KEY (specials_id),
                          KEY idx_specials_products_id (products_id)
);

DROP TABLE IF EXISTS whos_online;
CREATE TABLE whos_online (
                             customer_id int,
                             full_name varchar(255) NOT NULL,
                             session_id varchar(128) NOT NULL,
                             ip_address varchar(15) NOT NULL,
                             time_entry varchar(14) NOT NULL,
                             time_last_click varchar(14) NOT NULL,
                             last_page_url text NOT NULL,
                             host_address text NOT NULL,
                             user_agent varchar(255) NOT NULL default '',
                             KEY idx_whos_online_session_id (session_id)
) ;

DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions (
                          sesskey varchar(128) NOT NULL,
                          expiry int(11) unsigned NOT NULL,
                          value text NOT NULL,
                          PRIMARY KEY (sesskey)
);

DROP TABLE IF EXISTS featured;
CREATE TABLE featured (
                          featured_id int(11) NOT NULL auto_increment,
                          products_id bigint(20) NOT NULL default '0',
                          featured_date_added datetime default NULL,
                          featured_last_modified datetime default NULL,
                          expires_date date NOT NULL default '0001-01-01',
                          date_status_change datetime default NULL,
                          status int(1) NOT NULL default '1',
                          featured_date_available date NOT NULL default '0001-01-01',
                          PRIMARY KEY  (featured_id),
                          KEY idx_status_zen (status),
                          KEY idx_products_id_zen (products_id),
                          KEY idx_date_avail_zen (featured_date_available),
                          KEY idx_expires_date_zen (expires_date)
);

DROP TABLE IF EXISTS coupons;
CREATE TABLE coupons (
                         coupon_id int(11) NOT NULL auto_increment,
                         coupon_type char(1) NOT NULL default 'F',
                         coupon_code varchar(32) NOT NULL default '',
                         coupon_amount decimal(15,4) NOT NULL default '0.0000',
                         coupon_minimum_order decimal(15,4) NOT NULL default '0.0000',
                         coupon_start_date datetime NOT NULL default '0001-01-01 00:00:00',
                         coupon_expire_date datetime NOT NULL default '0001-01-01 00:00:00',
                         uses_per_coupon int(5) NOT NULL default 1,
                         uses_per_user int(5) NOT NULL default 0,
                         restrict_to_products varchar(255) default NULL,
                         restrict_to_categories varchar(255) default NULL,
                         coupon_active char(1) NOT NULL default 'Y',
                         date_created datetime NOT NULL default '0001-01-01 00:00:00',
                         date_modified datetime NOT NULL default '0001-01-01 00:00:00',
                         coupon_order_limit int(4) NOT NULL default 0,
                         PRIMARY KEY (coupon_id),
                         KEY idx_active_type_zen (coupon_active,coupon_type),
                         KEY idx_coupon_code_zen (coupon_code),
                         KEY idx_coupon_type_zen (coupon_type)
);

DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
                            categories_id int NOT NULL auto_increment,
                            categories_name varchar(64) NOT NULL,
                            categories_image varchar(64) NULL,
                            parent_id int DEFAULT '0' NOT NULL,
                            sort_order int(3),
                            date_added datetime,
                            last_modified datetime,
                            categories_status tinyint(1) NOT NULL default '1',
                            PRIMARY KEY (categories_id),
                            KEY idx_categories_parent_id (parent_id)
);

DROP TABLE IF EXISTS coupon_redeem_track;
CREATE TABLE coupon_redeem_track (
                                     unique_id int(11) NOT NULL auto_increment,
                                     coupon_id int(11) NOT NULL default '0',
                                     customer_id bigint(20) NOT NULL default '0',
                                     redeem_date datetime NULL,
                                     redeem_ip varchar(40) NULL,
                                     order_id int NULL,
                                     PRIMARY KEY  (unique_id),
                                     KEY idx_coupon_id_track (coupon_id)
);


DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
                        orders_id int NOT NULL auto_increment,
                        customers_id int NOT NULL,
                        customers_name varchar(255) NOT NULL,
                        customers_company varchar(255),
                        delivery_name varchar(255) NOT NULL,
                        delivery_company varchar(255),
                        delivery_street_address varchar(255) NOT NULL,
                        delivery_suburb varchar(255),
                        delivery_city varchar(255) NOT NULL,
                        delivery_postcode varchar(255) NOT NULL,
                        delivery_state varchar(255),
                        delivery_country varchar(255) NOT NULL,
                        delivery_date datetime NULL,
                        billing_name varchar(255) NOT NULL,
                        billing_company varchar(255),
                        billing_street_address varchar(255) NOT NULL,
                        billing_suburb varchar(255),
                        billing_city varchar(255) NOT NULL,
                        billing_postcode varchar(255) NOT NULL,
                        billing_state varchar(255),
                        billing_country varchar(255) NOT NULL,
                        payment_method varchar(255) NOT NULL,
                        shipping_method varchar(255) default NULL,
                        coupon_code varchar(32) NOT NULL default '',
                        date_purchased datetime,
                        orders_status int(5) NOT NULL,
                        orders_date_finished datetime,
                        order_total decimal(15,4) default NULL,
                        order_tax decimal(15,4) default NULL,
                        ip_address varchar(96) NOT NULL default '',
                        order_weight float default NULL,
                        last_modified datetime,
                        PRIMARY KEY (orders_id),
                        KEY idx_orders_customers_id (customers_id),
                        KEY idx_status_orders_cust (orders_status,orders_id,customers_id),
                        KEY idx_date_purchased (date_purchased),
                        KEY idx_cust_id_orders_id (customers_id,orders_id)
);